CREATE TABLE IF NOT EXISTS CUSTOMER (
	customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	first_name VARCHAR (255) not null,
	last_name VARCHAR (255) not null
);

CREATE TABLE IF NOT EXISTS ADDRESS (
  address_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  street_name VARCHAR (255) not null,
  street_nr INT not null,
  street_extension VARCHAR (10),
  zip_code VARCHAR (6) not null,
  city VARCHAR not null,
  country VARCHAR (100) not null,
  cust_id BIGINT not null,
  FOREIGN KEY (cust_id)
  REFERENCES CUSTOMER(customer_id)
);

CREATE TABLE IF NOT EXISTS INVOICE (
  invoice_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  invoice_type VARCHAR(100) not null,
  invoice_date DATE not null,
  payment_due_date DATE not null,
  start_date DATE not null,
  end_date DATE not null,
  amount DOUBLE not null,
  vat_amount DOUBLE not null,
  invoice_number BIGINT not null,
  addr_id BIGINT not null,
  FOREIGN KEY (addr_id)
  REFERENCES ADDRESS(address_id)
);

insert into customer (first_name, last_name) values ('John', 'Spangenberg');
insert into customer (first_name, last_name) values ('Joris', 'van Uffelen');
insert into customer (first_name, last_name) values ('Peter', 'de Boer');

insert into address (street_name, street_nr, zip_code, city, country, cust_id)
values ('Willaertstraat', 22, '1075LH', 'Amsterdam', 'The Netherlands', 1);

insert into address (street_name, street_nr, zip_code, city, country, cust_id)
values ('Zwaluwenveld', 13, '2727DJ', 'Zoetermeer', 'The Netherlands', 2);

insert into address (street_name, street_nr, zip_code, city, country, cust_id)
values ('Frans Halsstraat', 40, '1072BS', 'Amsterdam', 'The Netherlands', 3);

insert into invoice (invoice_type, invoice_date, payment_due_date, start_date, end_date, amount, vat_amount, invoice_number, addr_id)
values ('AdvancePayment', '2015-04-15','2015-04-30', '2015-05-01', '2015-06-01', 165.29, 34.71, '157005888', 1);

insert into invoice (invoice_type, invoice_date, payment_due_date, start_date, end_date, amount, vat_amount, invoice_number, addr_id)
values ('AdvancePayment', '2015-04-15','2015-04-30', '2015-05-01', '2015-06-01', 165.29, 34.71, '157005889', 1);

insert into invoice (invoice_type, invoice_date, payment_due_date, start_date, end_date, amount, vat_amount, invoice_number, addr_id)
values ('AdvancePayment', '2015-04-15','2015-04-30', '2015-05-01', '2015-06-01', 165.29, 34.71, '167005888', 2);

insert into invoice (invoice_type, invoice_date, payment_due_date, start_date, end_date, amount, vat_amount, invoice_number, addr_id)
values ('AdvancePayment', '2015-04-15','2015-04-30', '2015-05-01', '2015-06-01', 165.29, 34.71, '167005889', 2);


